config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :questions do
    resources :votings
    resources :comments

  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :option_a
  validates_presence_of :option_b

  has_many :votings, as: :voteable

  def show_votes_a
    upvotes = self.votings.where("up_vote = true").length
    return upvotes
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  has_many :questions

end

app/models/voting.rb
class Voting < ActiveRecord::Base
  belongs_to :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create!(question_params)
    if @question.save
      # current_user.question.push(@question)
      flash[:notice] = "Your question has been posted."
      redirect_to questions_path()
    else
      render :new
    end
end

  def show
    @questions = Question.all
    @question = Question.find(params[:id])
    @votes_a = @question.show_votes_a
  end

def upvote
  @question = Question.find params[:id]
  current_user.upvote(@question)
  flash[:message] = 'Thanks for voting!'
  redirect_to questions_path()
rescue MakeVoteable::Exceptions::AlreadyVotedError
  flash[:error] = 'Already voted!'
  redirect_to questions_path()
end

def downvote
  @question = Question.find params[:id]
  current_user.downvote(@question)
  flash[:message] = 'Thanks for voting!'
  redirect_to question_path(@question)
rescue MakeVoteable::Exceptions::AlreadyVotedError
  flash[:error] = 'Already voted!'
  redirect_to question_path(@question)
end

  private

  def question_params
    params.require(:question).permit(:option_a, :option_b)
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  # def new
  #   @question = Question.find(params[:id])
  #   @vote = Voting.new
  # end

  def create
    @question = Question.find(params[:question_id])
    @vote = Voting.new(voting_params)
    if @vote.save
      # current_user.questions << @vote
      @question.votings << @vote
      flash[:notification] = "Voted successfully"
      redirect_to questions_path
    else
      flash[:alert] = "Nope."
      redirect_to :back
    end
  end

  private

  def voting_params
    params.require(:voting).permit(:voteable_id, :up_vote)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
hi

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choose</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top" role='navigation'>
        <ul class='nav navbar-nav'>
          <li><%= link_to "Home", '/' %></li>
          <li><%= link_to "Questions", questions_path %></li>
          <li><%= link_to "Add a Question", new_question_path %></li>
        </ul>
      </nav>
    <%= flash[:notification] %>
    <%= flash[:alert] %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question%>

<%= form_for @question do |f| %>
  <div class="field">
    <%= f.text_field :option_a %><br>
    <%= f.label :option_a %>
    <div class="field">
      <%= f.text_field :option_b %><br>
      <%= f.label :option_b %>
    </div><br>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<%= form_for @question do |f| %>
  <div class="field">
    <%= link_to "Vote", question_votings_path(question, voting: { up_vote: true, voteable_id: question.id}), method: :post, class: "btn btn-success" %>
    <%= f.label :option_a, question.option_a %>
    <p> Votes: <%= @question.show_votes_a %> </p>
  <div class="field">
    <%= link_to "Vote", question_votings_path(question, voting: { up_vote: false, voteable_id: question.id}), method: :post, class: "btn btn-success" %>
    <%= f.label :option_b, question.option_b %>
  </div>
  <hr>
<% end %>

app/views/questions/index.html.erb
<h2>Questions</h2>




<%= render @questions %>

app/views/questions/new.html.erb
<h2>Add a Question</h2>

<%= render "form" %>

app/views/questions/show.html.erb
<h3>Show</h3>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>